compressionLevel: mixed

enableGlobalCache: false

nodeLinker: pnp

plugins:
  - path: .yarn/plugins/yarn-plugin-echoscript.cjs
    spec: 'https://raw.githubusercontent.com/taeyoon0137/echoscript/main/packages/plugin/plugin/bundle.js'

yarnPath: .yarn/releases/yarn-4.0.2.cjs
